<template>
  <d2-container>
    <mk-grid
      :option.sync="gridOption"
      :queryForm.sync="queryWidgetForm"
      :addForm.sync="addWidgetForm"
      :editForm.sync="modifyWidgetForm"
      :toolButtos="toolButtos"
      :toolbarRight="toolbarRight"
      :parameter="parameter"
      :url="Interface.tableInterface"
      :importUrl="Interface.importInterface"
      :exportUrl="Interface.exportInterface"
      :operateBtn="operateBtn"
      ref="mkGrid"
    >
    </mk-grid>
  </d2-container>
</template>	
		<script>
export default {
  name: "",
  data() {
    return {
      //table 配置项
      gridOption: {
        rowId: "jobno",
        columns: [
          {
            seq: null,
            title: "全选",
            width: "80",
            visible: true,
            resizable: null,
            align: "left",
            remoteSort: false,
            is_query: null,
            is_modify: null,
            is_add: null,
            fieldtype: null,
            type: "checkbox",
          },
          {
            seq: null,
            title: "操作",
            width: null,
            visible: true,
            resizable: null,
            align: "center",
            remoteSort: false,
            is_query: null,
            is_modify: null,
            is_add: null,
            fieldtype: null,
            fixed: "right",
            slots: {},
            field: "operate_id",
          },
          {
            seq: null,
            title: "工号",
            width: null,
            visible: true,
            resizable: null,
            align: "center",
            remoteSort: true,
            is_query: null,
            is_modify: null,
            is_add: null,
            fieldtype: null,
            slots: {},
            field: "jobno",
          },
          {
            seq: null,
            title: "部门",
            width: null,
            visible: true,
            resizable: null,
            align: "center",
            remoteSort: true,
            is_query: true,
            is_modify: null,
            is_add: null,
            fieldtype: "select",
            slots: {},
            field: "orgdeptname",
          },
          {
            seq: null,
            title: "姓名",
            width: null,
            visible: true,
            resizable: null,
            align: "center",
            remoteSort: true,
            is_query: true,
            is_modify: null,
            is_add: null,
            fieldtype: "input",
            slots: {},
            field: "name",
          },
          {
            seq: null,
            title: "性别",
            width: null,
            visible: true,
            resizable: null,
            align: "center",
            remoteSort: true,
            is_query: null,
            is_modify: null,
            is_add: null,
            fieldtype: null,
            slots: {},
            field: "sex",
          },
          {
            seq: null,
            title: "身份证",
            width: null,
            visible: true,
            resizable: null,
            align: "center",
            remoteSort: true,
            is_query: null,
            is_modify: null,
            is_add: null,
            fieldtype: null,
            slots: {},
            field: "idtype",
          },
          {
            seq: null,
            title: "出生日期",
            width: null,
            visible: true,
            resizable: null,
            align: "center",
            remoteSort: true,
            is_query: null,
            is_modify: null,
            is_add: null,
            fieldtype: null,
            slots: {},
            field: "birthday",
          },
          {
            seq: null,
            title: "年龄",
            width: null,
            visible: true,
            resizable: null,
            align: "center",
            remoteSort: true,
            is_query: null,
            is_modify: null,
            is_add: null,
            fieldtype: null,
            slots: {},
            field: "age",
          },
          {
            seq: null,
            title: "婚姻",
            width: null,
            visible: true,
            resizable: null,
            align: "center",
            remoteSort: true,
            is_query: null,
            is_modify: null,
            is_add: null,
            fieldtype: null,
            slots: {},
            field: "marriage",
          },
          {
            seq: null,
            title: "联系电话",
            width: null,
            visible: true,
            resizable: null,
            align: "center",
            remoteSort: true,
            is_query: null,
            is_modify: null,
            is_add: null,
            fieldtype: null,
            slots: {},
            field: "telno",
          },
          {
            seq: null,
            title: "预约套餐",
            width: null,
            visible: true,
            resizable: null,
            align: "center",
            remoteSort: true,
            is_query: null,
            is_modify: null,
            is_add: null,
            fieldtype: null,
            slots: {},
            field: "yytc",
          },
          {
            seq: null,
            title: "预约日期",
            width: null,
            visible: true,
            resizable: null,
            align: "center",
            remoteSort: true,
            is_query: null,
            is_modify: null,
            is_add: null,
            fieldtype: null,
            slots: {},
            field: "yyrq",
          },
          {
            seq: null,
            title: "部门负责人",
            width: null,
            visible: true,
            resizable: null,
            align: "center",
            remoteSort: true,
            is_query: null,
            is_modify: null,
            is_add: null,
            fieldtype: null,
            slots: {},
            field: "bmfzr",
          },
          {
            seq: null,
            title: "职务",
            width: null,
            visible: true,
            resizable: null,
            align: "center",
            remoteSort: true,
            is_query: null,
            is_modify: null,
            is_add: null,
            fieldtype: null,
            slots: {},
            field: "position",
          },
          {
            seq: null,
            title: "所属部门",
            width: null,
            visible: true,
            resizable: null,
            align: "center",
            remoteSort: true,
            is_query: null,
            is_modify: null,
            is_add: null,
            fieldtype: null,
            slots: {},
            field: "ssbm",
          },
          {
            seq: null,
            title: "预约状态",
            width: null,
            visible: false,
            resizable: null,
            align: "center",
            remoteSort: true,
            is_query: true,
            is_modify: null,
            is_add: null,
            fieldtype: "select",
            slots: {},
            field: "status",
          },
          {
            seq: null,
            title: "联系邮箱",
            width: null,
            visible: true,
            resizable: null,
            align: "center",
            remoteSort: true,
            slots: {},
            field: "email",
          },
        ],
        editRules: {},
        toolbar: {
          slots: { buttons: "toolbar_buttons", tools: "toolbar_right" },
          perfect: true,
          import: true,
          export: true,
          print: false,
          refresh: false,
          zoom: true,
          custom: true,
        },
      },
      //table表格查询字段
      queryWidgetForm: {
        list: [
          {
            type: "select",
            name: "部门",
            icon: "icon-select",
            options: {
              defaultValue: "",
              span: 8,
              multiple: false,
              disabled: false,
              clearable: false,
              placeholder: "",
              required: false,
              requiredMessage: "",
              showLabel: true,
              width: "100%",
              options: [
                { value: "Option 1" },
                { value: "Option 2" },
                { value: "Option 3" },
              ],
              remote: false,
              remoteType: "option",
              remoteOption: "",
              filterable: false,
              remoteOptions: [],
              props: { value: "bzcode", label: "bzname" },
              remoteFunc: "",
              customClass: "",
              labelWidth: 100,
              isLabelWidth: false,
              hidden: false,
              dataBind: true,
            },
            key: "1608001468272_dept_query",
            model: "orgid",
            rules: [],
          },
          {
            type: "input",
            name: "姓名",
            icon: "icon-input",
            options: {
              width: "100%",
              span: 8,
              defaultValue: "",
              required: false,
              requiredMessage: "",
              dataType: "",
              dataTypeCheck: false,
              dataTypeMessage: "",
              pattern: "",
              patternCheck: false,
              patternMessage: "",
              placeholder: "",
              customClass: "",
              disabled: false,
              labelWidth: 100,
              isLabelWidth: false,
              hidden: false,
              dataBind: true,
              showPassword: false,
              remoteFunc: "",
              remoteOption: "",
            },
            key: "1608001468272_name_query",
            model: "condition",
            rules: [],
          },
          {
            type: "select",
            name: "预约状态",
            icon: "icon-select",
            options: {
              defaultValue: "",
              span: 8,
              multiple: false,
              disabled: false,
              clearable: false,
              placeholder: "",
              required: false,
              requiredMessage: "",
              showLabel: true,
              width: "100%",
              options: [
                { value: "Option 1" },
                { value: "Option 2" },
                { value: "Option 3" },
              ],
              remote: false,
              remoteType: "option",
              remoteOption: "",
              filterable: false,
              remoteOptions: [],
              props: { value: "bzcode", label: "bzname" },
              remoteFunc: "",
              customClass: "",
              labelWidth: 100,
              isLabelWidth: false,
              hidden: false,
              dataBind: true,
            },
            key: "1608001468272_status_query",
            model: "status",
            rules: [],
          },
        ],
        config: {
          labelWidth: 100,
          labelPosition: "right",
          size: "small",
          customClass: "",
          ui: "element",
          layout: "horizontal",
          labelCol: 3,
          width: "100%",
          hideLabel: false,
          hideErrorMessage: false,
        },
      },
      //弹窗新增数据
      addWidgetForm: {
        list: [],
        config: {
          labelWidth: 100,
          labelPosition: "right",
          size: "small",
          customClass: "",
          ui: "element",
          layout: "horizontal",
          labelCol: 3,
          width: "100%",
          hideLabel: false,
          hideErrorMessage: false,
        },
      },
      //弹窗编辑数据
      modifyWidgetForm: {
        list: [],
        config: {
          labelWidth: 100,
          labelPosition: "right",
          size: "small",
          customClass: "",
          ui: "element",
          layout: "horizontal",
          labelCol: 3,
          width: "100%",
          hideLabel: false,
          hideErrorMessage: false,
        },
      },
      //工具栏左侧自定义按钮
      toolButtos: [],
      //工具栏右侧自定义按钮目前只有导入 导出
      toolbarRight: { import: "1", export: "1", print: "0" },
      //table 行操作列按钮
      operateBtn: ["edit", "del"],
      //table数据接口地址 导入 导出接口地址
      Interface: {
        tableInterface: "/Publics/MemberManage/Portal/ExamMemberInfo",
        importInterface: "/Publics/MemberManage/Portal/Import",
        exportInterface: "",
      },
      //附加参数
      parameter: {},
    };
  },
  computed: {},
  watch: {},
  //如果页面有keep-alive缓存功能，这个函数会触发
  activated() {},
  created() {
    // this.$refs.mkGrid.reload();
  },
  methods: {},
  mounted() {},
  //生命周期 - 创建之前
  beforeCreate() {},
  //生命周期 - 挂载之前
  beforeMount() {},
  //生命周期 - 更新之前
  beforeUpdate() {},
  //生命周期 - 更新之后
  updated() {},
  //生命周期 - 销毁之前
  beforeDestroy() {},
  //生命周期 - 销毁完成
  destroyed() {},
};
</script>
		<style scoped>
</style>
		